# @format

version: "2"

services:
  frontend:
    image: "raid/aksara-jawa-frontend:latest"
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 8080:80
  backend:
    image: "raid/aksara-jawa-backend:latest"
    build: ./Backend
    ports:
      - 14022:14022
